apiVersion: v1
kind: Service
metadata:
  name: svc-hellospring
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: app-hellospring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-hellospring
  namespace: default
spec:
  replicas: 2  # 가용성을 위해 2개 이상의 레플리카 권장
  selector:
    matchLabels:
      app: app-hellospring
  strategy:
    type: Recreate  # 배포 전략을 Recreate로 변경
  template:
    metadata:
      labels:
        app: app-hellospring
    spec:
      # 노드풀명과 노드명을 설정하여 Pod가 특정 노드에 배포되도록 지정
      nodeSelector:
        kubernetes.io/hostname: aks-nodechan4756-14963050-vmss000000  # 특정 노드로 설정
      containers:
      - name: container-hellospring
        image: acrchan4756.azurecr.io/hellospring:latest  # 또는 특정 태그 사용
        ports:
        - containerPort: 8081
        env:
        - name: TZ
          value: Asia/Seoul
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
