apiVersion: v1
kind: Service
metadata:
  name: svc-hellospring
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: app-hellospring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-hellospring
  namespace: default
spec:
  replicas: 2  # 가용성을 위해 2개 이상의 레플리카 권장
  selector:
    matchLabels:
      app: app-hellospring
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: app-hellospring
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: container-hellospring
        image: acrchan4756.azurecr.io/hellospring:latest  # 또는 특정 태그 사용
        ports:
        - containerPort: 8081
        env:
        - name: TZ
          value: Asia/Seoul
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /actuator/health  # 스프링부트 헬스 체크 엔드포인트
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 15
