apiVersion: v1
kind: Service
metadata:
  name: svc-hellospring
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: app-hellospring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-hellospring
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-hellospring
strategy:
  type: RollingUpdate  # 롤링 업데이트 전략 설정
  rollingUpdate:
    maxUnavailable: 1  # 최대 불가용한 Pod 수
    maxSurge: 1        # 최대 초과로 배포할 수 있는 Pod 수
  template:
    metadata:
      labels:
        app: app-hellospring
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: container-hellospring
          image: acrchan4756.azurecr.io/hellospring:latest
     
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 1Gi
          env:
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 8081
