apiVersion: v1
kind: Service
metadata:
  name: svc-hellospring
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: app-hellospring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-hellospring
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-hellospring
  template:
    metadata:
      labels:
        app: app-hellospring
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: container-hellospring
          image: acrchan4756.azurecr.io/hellospring:latest
     
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          env:
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 8081
