name: Build and Deploy to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "acrchan4756"
  CONTAINER_NAME: "hellospring"
  RESOURCE_GROUP: "rg-aks-dev"
  CLUSTER_NAME: "aks-chan4756"
  DEPLOYMENT_MANIFEST_PATH: "manifests/deployment.yaml"

jobs:
  build:
    name: Build and Push to ACR
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build

    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Configure Kubernetes Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          use-kubelogin: true
          admin: false

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
